name: Lint

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Tools
        run: |
          pip install black isort flake8 mypy bandit

      - name: Run Black
        run: black --check .

      - name: Run isort
        run: isort --check-only .

      - name: Run Flake8
        run: flake8 .

      - name: Run Mypy
        run: mypy .

      - name: Security Scan (Bandit)
        run: bandit -r .